# Deploy JS game to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]

env:
  JAVA_DISTRIBUTION: zulu
  JAVA_VERSION: 11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v4 }
      - { name: Set up JDK, uses: actions/setup-java@v3, with: { distribution: "${{ env.JAVA_DISTRIBUTION }}", java-version: "${{ env.JAVA_VERSION }}" } }
      - { name: Prepare Gradle, uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc } # v2.8.0
      - { name: Buid JS bundle, run: ./gradlew jsBrowserProductionWebpack }
      - name: Deploy ðŸš€ to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: github-pages # The branch the action should deploy to.
          FOLDER: build/dist/js/productionExecutable # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
